- name: Deploy and restart
  hosts: localhost
  
  tasks:
    - name: Deploy
      copy:
        src: target/maven-web-application.war
        dest: /opt/tomcat/webapps/
        owner: tomcat
        group: tomcat        
        mode: 0644
