- name: Deploy and restart
  hosts: webcontainers
  
  tasks:
    - name: Deploy
      become: true
      become_user: tomcat
      copy:
        src: target/maven-web-application.war
        dest: /opt/tomcat/webapps/
        owner: tomcat
        group: tomcat        
        mode: 0644

    - name: Reboot the container
      reboot:
          msg: "Reboot initiated by Ansible"
