- name: launch ec2 instance
  hosts: 127.0.0.1
  tasks:
    - name: instance create
      ec2:
            aws_access_key: xxx
            aws_secret_key: xxx
            security_token: xxx
            key_name: assignment
            instance_type: t2.micro
            image: ami-0747bdcabd34c712a
            region: us-east-1
            count: 1
            wait: yes
            instance_tags:
                Name: ansible
